### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by bosmart** [aspotashev/tesseract-ocr-cmake#1]
tesseract-ocr-cmake/ccstruct/blobbox.cpp:26:10: fatal error: 'allheaders.h' file not found
# include "allheaders.h"

```
     ^
```

49 warnings and 1 error generated.
make[2]: **\* [ccstruct/CMakeFiles/tesseract_ccstruct_static.dir/blobbox.cpp.o] Error 1
make[1]: **\* [ccstruct/CMakeFiles/tesseract_ccstruct_static.dir/all] Error 2
make: **\* [all] Error 2

Leptonica is installed.

**Comment by aspotashev** [comment]
You need to set the variable LEPTONICA_INCLUDE_DIRS to the path where allheaders.h is installed. See CMakeLists.txt.

**Comment by bosmart** [comment]
It builds now, thanks! But, when I try to build it together with the first example from https://code.google.com/p/tesseract-ocr/wiki/APIExample, I get the following weird error:

Undefined symbols for architecture x86_64:
  "tesseract::TessBaseAPI::SetImage(Pix const*)", referenced from:
      _main in tess.cpp.o
ld: symbol(s) not found for architecture x86_64

Interestingly enough the other SetImage function works fine.
